// Date: 8/31/2013 10:55:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelMountedTurret extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer BaseSide1;
    ModelRenderer BaseSide2;
    ModelRenderer BaseSide3;
    ModelRenderer BaseSide4;
    ModelRenderer TurretMount;
    ModelRenderer GunAssembly;
  
  public ModelMountedTurret()
  {
    textureWidth = 256;
    textureHeight = 64;
    setTextureOffset("Base.Base1", 0, 0);
    setTextureOffset("Base.Base2", 0, 0);
    setTextureOffset("TurretMount.Ball1", 0, 0);
    setTextureOffset("TurretMount.Ball2", 0, 0);
    setTextureOffset("TurretMount.MountPost1", 0, 0);
    setTextureOffset("GunAssembly.BarrelMountPlate1", 0, 0);
    setTextureOffset("GunAssembly.Barrel11", 0, 0);
    setTextureOffset("GunAssembly.BarrelBase11", 0, 0);
    setTextureOffset("GunAssembly.Barrel12", 0, 0);
    setTextureOffset("GunAssembly.BarrelMountPlate2", 0, 0);
    setTextureOffset("GunAssembly.BarrelMount2", 0, 0);
    setTextureOffset("GunAssembly.BarrelBase21", 0, 0);
    setTextureOffset("GunAssembly.BarrelBase22", 0, 0);
    setTextureOffset("GunAssembly.BarrelBase23", 0, 0);
    setTextureOffset("GunAssembly.Barrel21", 0, 0);
    setTextureOffset("GunAssembly.Barrel22", 0, 0);
    setTextureOffset("GunAssembly.Barrel23", 0, 0);
    
    Base = new ModelRenderer(this, "Base");
    Base.setRotationPoint(-8F, 22F, -8F);
    setRotation(Base, 0F, 0F, 0F);
    Base.mirror = true;
      Base.addBox("Base1", 0F, 0F, 0F, 32, 2, 32);
      Base.addBox("Base2", 9F, -1F, 3F, 14, 1, 26);
      BaseSide1 = new ModelRenderer(this, 0, 0);
      BaseSide1.addBox(0F, 0F, 0F, 14, 1, 12);
      BaseSide1.setRotationPoint(1F, 21F, -5F);
      BaseSide1.setTextureSize(256, 64);
      BaseSide1.mirror = true;
      setRotation(BaseSide1, 0.0872665F, 0F, 0F);
      BaseSide2 = new ModelRenderer(this, 0, 0);
      BaseSide2.addBox(0F, 0F, 0F, 14, 1, 12);
      BaseSide2.setRotationPoint(1F, 20F, 9F);
      BaseSide2.setTextureSize(256, 64);
      BaseSide2.mirror = true;
      setRotation(BaseSide2, -0.0872665F, 0F, 0F);
      BaseSide3 = new ModelRenderer(this, 0, 0);
      BaseSide3.addBox(0F, 0F, 0F, 10, 1, 26);
      BaseSide3.setRotationPoint(-8F, 22F, -5F);
      BaseSide3.setTextureSize(256, 64);
      BaseSide3.mirror = true;
      setRotation(BaseSide3, 0F, 0F, -0.0872665F);
      BaseSide4 = new ModelRenderer(this, 0, 0);
      BaseSide4.addBox(0F, 0F, 0F, 10, 1, 26);
      BaseSide4.setRotationPoint(14F, 21F, -5F);
      BaseSide4.setTextureSize(256, 64);
      BaseSide4.mirror = true;
      setRotation(BaseSide4, 0F, 0F, 0.0872665F);
    TurretMount = new ModelRenderer(this, "TurretMount");
    TurretMount.setRotationPoint(5F, 15F, 5F);
    setRotation(TurretMount, 0F, 0F, 0F);
    TurretMount.mirror = true;
      TurretMount.addBox("Ball1", -1F, -10F, -4F, 8, 10, 14);
      TurretMount.addBox("Ball2", -2F, -9F, -4F, 10, 8, 14);
      Ball3 = new ModelRenderer(this, 0, 0);
      Ball3.addBox(1F, 7F, 4F, 2, 6, 8);
      Ball3.setRotationPoint(0F, 0F, 0F);
      Ball3.setTextureSize(256, 64);
      Ball3.mirror = true;
      setRotation(Ball3, 0F, 0F, 0F);
      TurretMount.addBox("MountPost1", 0F, 0F, 0F, 6, 7, 6);
    GunAssembly = new ModelRenderer(this, "GunAssembly");
    GunAssembly.setRotationPoint(5F, 15F, 5F);
    setRotation(GunAssembly, 0F, 0F, 0F);
    GunAssembly.mirror = true;
      GunAssembly.addBox("BarrelMountPlate1", 0F, -8F, -5F, 6, 6, 1);
      BarrelMount1 = new ModelRenderer(this, 0, 0);
      BarrelMount1.addBox(5F, 9F, -2.5F, 6, 2, 3);
      BarrelMount1.setRotationPoint(0F, 0F, 0F);
      BarrelMount1.setTextureSize(256, 64);
      BarrelMount1.mirror = true;
      setRotation(BarrelMount1, 0F, 0F, 0F);
      GunAssembly.addBox("Barrel11", -12F, -7F, -7F, 18, 1, 1);
      GunAssembly.addBox("BarrelBase11", -1F, -7.5F, -7.5F, 7, 2, 2);
      GunAssembly.addBox("Barrel12", -12F, -5.5F, -9F, 18, 1, 1);
      BarrelBase12 = new ModelRenderer(this, 0, 0);
      BarrelBase12.addBox(4F, 9F, -4.5F, 7, 2, 2);
      BarrelBase12.setRotationPoint(0F, 0F, 0F);
      BarrelBase12.setTextureSize(256, 64);
      BarrelBase12.mirror = true;
      setRotation(BarrelBase12, 0F, 0F, 0F);
      Barrel13 = new ModelRenderer(this, 0, 0);
      Barrel13.addBox(-12F, -4F, -7F, 18, 1, 1);
      Barrel13.setRotationPoint(5F, 15F, 5F);
      Barrel13.setTextureSize(256, 64);
      Barrel13.mirror = true;
      setRotation(Barrel13, 0F, 0F, 0F);
      BarrelBase13 = new ModelRenderer(this, 0, 0);
      BarrelBase13.addBox(4F, 10.5F, -2.5F, 7, 2, 2);
      BarrelBase13.setRotationPoint(0F, 0F, 0F);
      BarrelBase13.setTextureSize(256, 64);
      BarrelBase13.mirror = true;
      setRotation(BarrelBase13, 0F, 0F, 0F);
      GunAssembly.addBox("BarrelMountPlate2", 0F, -8F, 10F, 6, 6, 1);
      GunAssembly.addBox("BarrelMount2", 0F, -6F, 10.5F, 6, 2, 3);
      GunAssembly.addBox("BarrelBase21", -1F, -7.5F, 11.5F, 7, 2, 2);
      GunAssembly.addBox("BarrelBase22", -1F, -6F, 13.5F, 7, 2, 2);
      GunAssembly.addBox("BarrelBase23", -1F, -4.5F, 11.5F, 7, 2, 2);
      GunAssembly.addBox("Barrel21", -12F, -7F, 12F, 18, 1, 1);
      GunAssembly.addBox("Barrel22", -12F, -5.5F, 14F, 18, 1, 1);
      GunAssembly.addBox("Barrel23", -12F, -4F, 12F, 18, 1, 1);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Base.render(f5);
    BaseSide1.render(f5);
    BaseSide2.render(f5);
    BaseSide3.render(f5);
    BaseSide4.render(f5);
    TurretMount.render(f5);
    GunAssembly.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
